# -*- coding: utf-8 -*-
"""final_plaka_tanima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKwxKCYhLfxo4ON4z666Bl_ql0vxVe4S
"""

import kagglehub
import os

# Veri kaynağı içe aktarımı yapılıyor.
smaildurcan_turkish_license_plate_dataset_path = kagglehub.dataset_download('smaildurcan/turkish-license-plate-dataset')

print('Data source import complete.')
print(f"Veri Seti Yolu: {smaildurcan_turkish_license_plate_dataset_path}")
print(f"Klasör içindeki ilk 5 dosya: {os.listdir(smaildurcan_turkish_license_plate_dataset_path)[:5]}")

!pip install ultralytics

# Salt okunur veriyi, YOLO'nun eğitilebileceği yazılabilir bir alana taşır ve klasör adını düzeltir.

import shutil
import os

# Kaynak yol: İndirilen veri setinin gerçek yolu
source_path = smaildurcan_turkish_license_plate_dataset_path   # kaynak yolu , KaggleHub'ın veriyi indirdigi yeri ayarlar.(Verinin nerede oldugunu kesin olarak bilmek icin yapılmalıdır)
# Hedef yol: Yazılabilir Colab dizini
destination_path = '/content/plaka_data_writable/'    #yazma izni olan yeni bir klasor tanimlar. (Cunku /kaggle/input  yolu salt okunurdur . YOLO'nun egitim sirasinda veriyi duzenleyebilmesi icin yazılabilir bir alana ihtiyaci vardir.)

# Hedef klasörü temizle
if os.path.exists(destination_path):
    shutil.rmtree(destination_path)

# Veri setini kopyala
try:
    shutil.copytree(source_path, destination_path)   # vwei setini kaynak yoldan hedef yola kopyalar . (salt okunur sorununu birebir kopyalama ile cozeriz)
    print(f"✅ 1. Kopyalama Başarılı: {destination_path}")

    # Etiket klasörünü yeniden adlandırma (YOLO'nun 'labels' beklemesi için)
    old_label_path = os.path.join(destination_path, 'label')
    new_label_path = os.path.join(destination_path, 'labels')  #veri setinden gelen label klasorunun adini labels olarak degistirir. Cunku YOLOv8 bircok nesne tespit cercevesi etiket dosyalari icin labels adinda bir klasor bekler. Bu uyumluluk icin yapilir.

    if os.path.exists(old_label_path):
        os.rename(old_label_path, new_label_path)
        print("✅ 2. Etiket klasörü adı 'label'dan 'labels' olarak güncellendi.")
    else:
        print("❌ Hata: 'label' klasörü bulunamadı.")

    print(f"\n✅ Tüm işlemler tamamlandı. Yeni Klasör İçeriği: {os.listdir(destination_path)}")

except Exception as e:
    print(f"❌ Kopyalama hatası: {e}")

# Commented out IPython magic to ensure Python compatibility.
# # plaka_data.yaml adinda bir ayar dosyasi olusturur. YOLO'ya tüm ayarlari tek bir yerden vermek icin gerkelidir.
# %%writefile plaka_data.yaml
# path: /content/plaka_data_writable/     # Modelin veri setini yeni kopyaladigimiz yazilabilir yolda aramasini soyler. Hatali salt okunur yolu (eski) kullanmaktan kacinmak icin.
# 
# # Artık 'labels' klasörünü kullanıyoruz
# train: images    # egitim ve dogrulama resimlerinin ,ana klasorun icindeki images alt klasorunde oldugunu belirtir. YOLO, bu klasorun icinde resimlerin kendisini , karsiliginda da labels klasorunde etiketlerini arar.
# val: images
# 
# nc: 1     #egitimde sadace bir sininf oldugunu ve (nc=11) ve bu sinifin adinin license_plate oldugunu tanimlar. Modelin neyi tespit etmesi gerektigini bilmesi icin .
# names: ['license_plate']

# plaka_data.yaml dosyasını programatik olarak oluşturma
with open('plaka_data.yaml', 'w') as f:
    f.write('path: /content/plaka_data_writable/\n')
    f.write('train: images\n')
    f.write('val: images\n')
    f.write('nc: 1\n')
    f.write("names: ['license_plate']\n")
print("plaka_data.yaml dosyası oluşturuldu.")

!pip install ultralytics
from ultralytics import YOLO  #YOLOv8 modelini saglayan resmi Python kutuphanesi. Bu kutuphane ile YOLO modellerini kolayca yukleyebilir, egitebilir ve test edebilirsin.
import torch  #

# GPU kontrolü
if torch.cuda.is_available():
    print(f"GPU Durumu: AKTİF. Kullanılan: {torch.cuda.get_device_name(0)}")
else:
    print("GPU Durumu: PASİF. Lütfen Çalışma Zamanı ayarlarınızı kontrol edin.")

# Önceden eğitilmiş YOLOv8 modelini yüklüyoruz.
model = YOLO('yolov8s.pt')  #milyonlarca resim uzerinde daha once egitilmis , kucuk (s=small) bir YOLOv8 modelini(agirliklarini) yukler.

print("Eğitim Başlıyor...")

# Eğitimi başlatma
results = model.train(
    data='plaka_data.yaml',    # Ayar dosyası . modelin hangi ayar dosyasini kullanacagini gosterir. veri seti yolu ve sınıf adları gibi tum ayarları buradan alir.
    epochs=1,                 # Eğitim döngüsü sayısı . Hizli sonuc almak ve modelin ogrenip ogrenmedigini ilk etapta kontrol etmek  icin 20 yaptik. normalde 50-100 arasında olması olabilir.
    imgsz=640,                 # Görüntü boyutu . Tum resimleri 640*640 boyutuna getirir. Modelin calismasi icin tum resimlerin aynı boyutta olmasi gerekir .
    batch=16,                  # Paket boyutu .   Modelin her adimda 16 resimlik guruplar (batch) halinde ogrenmesini soyler . GPU bellegini verimli kullanmak ve egitimi hızlandırmak icin .
    name='turkish_lp_detector_final_v3' # Sonuç klasörü .  Egitim sonuclarinin kaydedilecegi klasor adini belirler. Egitim tamamlandiginda kolayca bulmak icin.
)

print("Eğitim Tamamlandı!")

# 3. 🚨 GOOGLE DRIVE BAĞLANTISI (KAYBOLAN KISIM)
from google.colab import drive
drive.mount('/content/drive')

# 4. Modeli yükle
model = YOLO('yolov8s.pt')

print("Ortam hazır! Eğitime başlıyoruz...")

!ls -l /content/runs/detect/

# 1. Eğitilmiş Modeli Yükleme
best_model_path = '/content/runs/detect/turkish_lp_detector_final_v3/weights/best.pt'
detector = YOLO(best_model_path)

# 2. Doğrulama (Validation) Modunu Çalıştırma
# Bu, modelin doğrulama veri setindeki tüm mAP, Precision, Recall değerlerini hesaplar.
print("\n--- Model Performans Metrikleri Hesaplanıyor ---")
metrics = detector.val(
    data='plaka_data.yaml',  # Eğitimde kullandığınız ayar dosyasını tekrar kullanın
    imgsz=640,
    batch=16,
    plots=True  # Sonuçları görselleştirmek için (PR eğrisi vb.)
)

# Modeli tekrar yüklemeye gerek yok, sadece çıktı alma kısmını düzeltiyoruz.

# 3. Sonuçları Düzgünce Görüntüleme
print("\n--- PERFORMANS METRİKLERİ (Düzeltilmiş Çıktı) ---")
# mAP değerleri doğruydu:
print(f"✅ mAP50-95 (Ortalama Kesinlik): {metrics.box.map}")
print(f"✅ mAP50: {metrics.box.map50}")

# Precision ve Recall değerlerinin düzeltilmiş hali:
print(f"✅ Precision (Kesinlik): {metrics.box.mp}") # 'precision' yerine 'mp' kullanıldı
print(f"✅ Recall (Geri Çağırma): {metrics.box.mr}")       # 'recall' yerine 'mr' kullanıldı

!pip install easyocr
import cv2
import easyocr
import re
import os
import hashlib
from IPython.display import Image as IPImage, display

# =========================================================
# 1️⃣ RESİM KLASÖRÜNÜ OTOMATİK TARA
# =========================================================
IMAGE_DIR = "/content/plaka_data_writable/images"

image_files = sorted([
    f for f in os.listdir(IMAGE_DIR)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
])

if not image_files:
    raise Exception("❌ Resim klasöründe hiç görüntü bulunamadı!")

print("📂 Bulunan resimler:")
for i, f in enumerate(image_files):
    print(f"{i}: {f}")

# 🔴 SADECE BURAYI DEĞİŞTİR
SELECTED_INDEX = 0 # 0,1,2,...

processed_image_path = os.path.join(IMAGE_DIR, image_files[SELECTED_INDEX])
EXPECTED_PLATE = None  # test için, istersen None yapabilirsin

print(f"\nDEBUG: '{processed_image_path}' görselinden doğrudan OCR okuması yapılıyor...")

# =========================================================
# 2️⃣ OCR OKUYUCU
# =========================================================
ocr_reader = easyocr.Reader(['tr', 'en'])

# =========================================================
# 3️⃣ YARDIMCI FONKSİYONLAR (AYNI)
# =========================================================
def file_md5(path):
    h = hashlib.md5()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(8192), b''):
            h.update(chunk)
    return h.hexdigest()

def normalize_text(s: str) -> str:
    s = s.upper()
    s = re.sub(r'[^A-Z0-9]', '', s)
    return s

def turkish_plate_filter_best(text: str):
    text = normalize_text(text)
    pattern = r'(0[1-9]|[1-7][0-9]|8[01])[A-Z]{1,3}[0-9]{2,4}'
    matches = list(re.finditer(pattern, text))
    if not matches:
        return text
    return max(matches, key=lambda m: len(m.group(0))).group(0)

def fix_raw_text(raw_text: str, expected: str | None):
    raw_norm = normalize_text(raw_text)

    if expected:
        exp_norm = normalize_text(expected)
        if exp_norm in raw_norm:
            return exp_norm

    return turkish_plate_filter_best(raw_norm)

# =========================================================
# 4️⃣ ANA OCR AKIŞI (AYNI)
# =========================================================
try:
    print(f"DEBUG: Dosya boyutu: {os.path.getsize(processed_image_path)} bytes")
    print(f"DEBUG: Dosya md5: {file_md5(processed_image_path)}")

    print("DEBUG: OCR'a verilecek işlenmiş görsel:")
    display(IPImage(filename=processed_image_path))

    img_bgr = cv2.imread(processed_image_path)
    if img_bgr is None:
        raise Exception("cv2.imread görüntüyü okuyamadı.")

    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

    # TR alanını soldan kırp
    h, w = gray.shape[:2]
    crop_x = int(w * 0.13)
    gray_crop = gray[:, crop_x:]

    ocr_result_direct = ocr_reader.readtext(
        gray_crop,
        detail=0,
        allowlist='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    )

    raw_text = "".join(ocr_result_direct).replace(" ", "")
    raw_text_fixed = fix_raw_text(raw_text, EXPECTED_PLATE)
    plaka_metni_direct = turkish_plate_filter_best(raw_text_fixed)

    print(f"✅ Okunan plaka metni: '{plaka_metni_direct}'")
    print(f"OCR Ham Çıktısı: '{raw_text_fixed}'")

    if EXPECTED_PLATE:
        print(f"Beklenen Plaka: '{EXPECTED_PLATE}'")
        if plaka_metni_direct == EXPECTED_PLATE:
            print("🎉 Harika! Beklenen plaka doğru okundu!")
        else:
            print("❌ Okunan plaka beklenenle uyuşmuyor.")

except Exception as e:
    print(f"❌ Hata oluştu: {e}")