# -*- coding: utf-8 -*-
"""FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKwxKCYhLfxo4ON4z666Bl_ql0vxVe4S
"""

# =======================
# SETUP- Gerekli Kutuphanelerin Kurulumu ve Ice Aktarilmasi
# =======================

# ultralytics: YOLOv8 modelini kullanmak icin gerekli kutuphane
# easyocr: Plaka uzerindeki metni okumak icin OCR (Optical Character Recognition) kutuphanesi
!pip install ultralytics easyocr

# kagglehub: Kaggle'dan veri setini indirmek icin kullanilir
# os, shutil: Dosya ve dizin islemleri icin sistem kutuphaneleri
# torch: PyTorch, derin ogrenme framework'u (GPU kontrolu icin kullanilacak)
# cv2: OpenCV, goruntu isleme kutuphanesi
# easyocr: OCR islemleri icin
# re: Duzenli ifadeler (regex) ile metin isleme
import kagglehub, os, shutil, torch, cv2, easyocr, re
from ultralytics import YOLO
from IPython.display import Image as IPImage, display

# =======================
# DATASET- Veri Setinin Indirilmesi ve Hazirlanmasi
# =======================

# Kaggle'dan Turk plaka veri setini indir
dataset = kagglehub.dataset_download('smaildurcan/turkish-license-plate-dataset')

# Veri setini yazilabilir bir dizine kopyalayacagiz (/content/plaka_data_writable)
dst = '/content/plaka_data_writable'

# Eger hedef dizin zaten varsa, icerigini temizle (onceki calistirmalardan kalan verileri sil)
if os.path.exists(dst):
    shutil.rmtree(dst)

# Veri setini hedef dizine kopyala
shutil.copytree(dataset, dst)

# YOLO etiket formati 'labels' klasoru bekler, veri setinde 'label' varsa adini degistir
if os.path.exists(f'{dst}/label'):
    os.rename(f'{dst}/label', f'{dst}/labels')

# YOLO egitimi icin gerekli yapilandirma dosyasini olustur (plaka_data.yaml)
# Bu dosya veri setinin konumunu ve sinif bilgilerini icerir
with open('plaka_data.yaml','w') as f:
    f.write(
        "path: /content/plaka_data_writable/\n"
        "train: images\nval: images\n"
        "nc: 1\nnames: ['license_plate']\n"
    )

print("Dataset hazır.")

# =======================
# TRAIN- Model Egitimi
# =======================

# GPU kullanilabilirligini kontrol et ve ekrana yazdir
# Egitim GPU'da cok daha hizli olacaktir
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "YOK")

# YOLOv8 small (yolov8s) on egitimli modelini yukle
# Bu model COCO veri setinde egitilmis genel bir nesne tespit modeli
model = YOLO('yolov8s.pt')

# Modeli Turk plaka veri setinde egit
model.train(
    data='plaka_data.yaml',
    epochs=1,
    imgsz=640,
    batch=16,
    name='turkish_lp_detector_final_v3'
)

# =======================
# VALIDATION - Modelin Performansini Degerlendirme
# =======================

# En iyi agirliklarin (best.pt) kaydedildigi yolu belirle
# Model egitimi sirasinda en iyi performansi gosteren agirliklar bu dosyaya kaydedilir
best = '/content/runs/detect/turkish_lp_detector_final_v3/weights/best.pt'

# En iyi agirliklari yukle
detector = YOLO(best)

# Modeli dogrulama veri seti uzerinde test et ve metriklerini hesapla
metrics = detector.val(data='plaka_data.yaml', imgsz=640, batch=16)

# Performans metriklerini ekrana yazdir
print("\n--- METRİKLER ---")
print(f"mAP50-95: {metrics.box.map}")
print(f"mAP50: {metrics.box.map50}")
print(f"Precision: {metrics.box.mp}")
print(f"Recall: {metrics.box.mr}")

# =======================
# OCR + ÇİZİM - Plaka Tespiti ve Karakter Tanima
# =======================

# Goruntulerin bulundugu dizini belirle
IMG_DIR = f'{dst}/images'

# Dizindeki 62. goruntuyu sec (index 61)
# jpg veya png uzantili dosyalari alfabetik sirala ve birini sec
img_name = sorted([f for f in os.listdir(IMG_DIR) if f.lower().endswith(('jpg','png'))])[61]
img_path = f"{IMG_DIR}/{img_name}"

# Secilen goruntuyu OpenCV ile oku (BGR formatinda)
img = cv2.imread(img_path)

# Orijinal goruntuyu Jupyter'da goster
display(IPImage(filename=img_path))

# YOLO tespiti
# conf=0.4: Guven esigi %40 (bunun uzerindeki tespitler kabul edilir)
res = detector(img_path, conf=0.4)[0]

# Eger hic plaka tespit edilmediyse hata ver
if not res.boxes:
    raise Exception("❌ Plaka bulunamadı")

# Ilk tespit edilen plakanin koordinatlarini al (x1,y1: sol ust kose, x2,y2: sag alt kose)
x1, y1, x2, y2 = map(int, res.boxes.xyxy[0])

# Plaka bolgesini orijinal goruntuден kirp (crop)
plate = img[y1:y2, x1:x2]

# =======================
# OCR - Plaka Uzerindeki Metni Okuma
# =======================

# EasyOCR okuyucusunu baslat (Turkce ve Ingilizce karakterleri taniyacak)
ocr = easyocr.Reader(['tr','en'])

# Plaka goruntusunu gri tonlamaya cevir (OCR icin daha iyi sonuc verir
g = cv2.cvtColor(plate, cv2.COLOR_BGR2GRAY)

# Goruntuyu 2 kat buyut (OCR dogrulagunu artirmak icin)
# INTER_CUBIC: Yuksek kaliteli interpolasyon yontemi
g = cv2.resize(g, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)

# Otsu esikleme ile ikili (binary) goruntu olustur (arka plan-on plan ayrimi)
# Bu islem metni arka plandan daha net ayirir
_, g = cv2.threshold(g, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

# OCR ile plaka metnini oku, sadece metni al (koordinat bilgisi istemiyoruz)
raw = "".join(ocr.readtext(g, detail=0))

# Okunan metinden sadece harf ve rakamlari al (bosluk, noktalama vb. temizle)
# Tum karakterleri buyuk harfe cevir
raw = re.sub(r'[^A-Z0-9]', '', raw.upper())

# Eger metin "TR" ile basliyorsa (bazi plakalarda ulke kodu olabilir), bunu kaldir
if raw.startswith("TR"):
    raw = raw[2:]

# Turk plaka formatini yakala: 2 rakam + 1-3 harf + 2-4 rakam
# Ornek: 34ABC1234, 06A1234, 81XYZ999
# Il kodlari 01-81 arasi (sadece 82 ve uzeri gecersiz)
m = re.search(r'(0[1-9]|[1-7][0-9]|8[01])[A-Z]{1,3}[0-9]{2,4}', raw)
raw = m.group(0) if m else raw

# OCR hata duzeltme sozlugu
# OCR bazen rakamlari harf olarak (veya tersini) okuyabilir, en yaygin hatalari duzelt
fix = {'Z':'7','O':'0','A':'4','S':'5','B':'8'}

# Akilli duzeltme fonksiyonu
# Ilk 2 karakter (il kodu) ve 3-5. karakterler (harfler) degistirilmez
# 6. karakterden sonraki karakterler (rakamlar) duzeltme sozlugune gore duzeltilir
def smart(text):
    return (
        text[:2] +
        text[2:5] +
        "".join(fix.get(c, c) for c in text[5:])
    )

# Akilli duzeltmeyi uygula
plate_text = smart(raw)

# Sonuclari ekrana yazdir
print("OCR Ham:", raw) # Duzeltme oncesi ham OCR ciktisi
print("✅ Okunan Plaka:", plate_text) # Duzeltme sonrasi nihai plaka metni

# =======================
# GÖRSEL ÜZERİNE ÇİZİM - Sonuclari Gorsellestirme
# =======================

# Orijinal goruntunun bir kopyasini olustur (uzerine cizim yapacagiz)
draw = img.copy()

# Tespit edilen plaka etrafina yesil dikdortgen ciz
# (x1,y1): Sol ust kose, (x2,y2): Sag alt kose
# (0,255,0): Yesil renk (BGR formatinda), 2: Cizgi kalinligi
cv2.rectangle(draw, (x1, y1), (x2, y2), (0,255,0), 2)

# Okunan plaka metnini dikdortgenin ustune yaz
cv2.putText(
    draw,  # Uzerine yazilacak goruntu
    plate_text,  # Yazilacak metin (okunan plaka)
    (x1, y1-10), # Metin pozisyonu (dikdortgenin hemen ustu)
    cv2.FONT_HERSHEY_SIMPLEX, # Font tipi
    0.9, # Font boyutu
    (0,255,0), # Metin rengi (yesil)
    2 # Metin kalinligi
)

# Sonuc goruntusunu Jupyter'da goster
# OpenCV goruntusunu JPEG formatina kodla ve goster
display(IPImage(data=cv2.imencode('.jpg', draw)[1].tobytes()))